/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;

import javax.swing.JOptionPane;

/**
 *
 * @author Diaa Dwikat
 */
public class addStudent extends javax.swing.JFrame {

    /**
     * Creates new form addStudent
     */
    public addStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ST1 = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 66, 74));

        jLabel1.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\title.png")); // NOI18N

        RN.setBackground(new java.awt.Color(60, 66, 74));
        RN.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RN.setForeground(new java.awt.Color(255, 255, 255));
        RN.setText("Registration Number");
        RN.setBorder(null);
        RN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RNFocusLost(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        FN.setBackground(new java.awt.Color(60, 66, 74));
        FN.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FN.setForeground(new java.awt.Color(255, 255, 255));
        FN.setText("Full Name");
        FN.setBorder(null);
        FN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FNFocusLost(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        BD.setBackground(new java.awt.Color(60, 66, 74));
        BD.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BD.setForeground(new java.awt.Color(255, 255, 255));
        BD.setText("Birth Date");
        BD.setBorder(null);
        BD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BDFocusLost(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        adress.setBackground(new java.awt.Color(60, 66, 74));
        adress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adress.setForeground(new java.awt.Color(255, 255, 255));
        adress.setText("Adress");
        adress.setBorder(null);
        adress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adressFocusLost(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        phone.setBackground(new java.awt.Color(60, 66, 74));
        phone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone");
        phone.setBorder(null);
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        email.setBackground(new java.awt.Color(60, 66, 74));
        email.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        email.setBorder(null);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        ST1.setBackground(new java.awt.Color(60, 66, 74));
        ST1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ST1.setForeground(new java.awt.Color(255, 255, 255));
        ST1.setText("Standard");
        ST1.setBorder(null);
        ST1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ST1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ST1FocusLost(evt);
            }
        });

        gender.setBackground(new java.awt.Color(60, 66, 74));
        gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female" }));

        add.setBackground(new java.awt.Color(133, 180, 220));
        add.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add.setForeground(new java.awt.Color(0, 51, 51));
        add.setText("ADD");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	addStudent(evt);
            }
        });

        back.setBackground(new java.awt.Color(133, 180, 220));
        back.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        back.setForeground(new java.awt.Color(0, 51, 51));
        back.setText("back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RN, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BD, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(gender, 0, 286, Short.MAX_VALUE)
                                        .addGap(467, 467, 467)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ST1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phone))))))
                .addGap(149, 149, 149))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))
                                .addGap(62, 62, 62)
                                .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(72, 72, 72)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addComponent(BD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ST1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RNFocusGained
        // TODO add your handling code here:
        if(RN.getText().equals("Registration Number"))
            RN.setText("");
    }//GEN-LAST:event_RNFocusGained

    private void RNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RNFocusLost
        // TODO add your handling code here:
        if(RN.getText().equals(""))
            RN.setText("Registration Number");
    }//GEN-LAST:event_RNFocusLost

    private void FNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FNFocusGained

        // TODO add your handling code here:
        if(FN.getText().equals("Full Name"))
            FN.setText("");
    }//GEN-LAST:event_FNFocusGained

    private void FNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FNFocusLost
        if(FN.getText().equals(""))
            FN.setText("Full Name");
        // TODO add your handling code here:
    }//GEN-LAST:event_FNFocusLost

    private void BDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDFocusGained
        // TODO add your handling code here:
        if(BD.getText().equals("Birth Date"))
            BD.setText("");
    }//GEN-LAST:event_BDFocusGained

    private void BDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDFocusLost
        // TODO add your handling code here:
        if(BD.getText().equals(""))
            BD.setText("Birth Date");
    }//GEN-LAST:event_BDFocusLost

    private void adressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adressFocusGained
        // TODO add your handling code here:
        if(adress.getText().equals("Adress"))
            adress.setText("");
    }//GEN-LAST:event_adressFocusGained

    private void adressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adressFocusLost
        // TODO add your handling code here:
        if(adress.getText().equals(""))
            adress.setText("Adress");
    }//GEN-LAST:event_adressFocusLost

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
        if(phone.getText().equals("Phone"))
            phone.setText("");
    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
        if(phone.getText().equals(""))
            phone.setText("Phone");
    }//GEN-LAST:event_phoneFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Email"))
            email.setText("");
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if(email.getText().equals(""))
            email.setText("Email");
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFocusLost

    private void ST1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ST1FocusGained
        if(ST1.getText().equals("Standard"))
            ST1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ST1FocusGained

    private void ST1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ST1FocusLost
        // TODO add your handling code here:
        if(ST1.getText().equals(""))
            ST1.setText("Standard");
    }//GEN-LAST:event_ST1FocusLost

    private void addStudent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String gender_2 = gender.getSelectedItem().toString();
        
        String name = FN.getText();
        String standard = ST1.getText();
        String adress_2 = adress.getText();
        String email_2 = email.getText();
        String phone_2 = phone.getText();
        String  date = BD.getText();
        String rn = RN.getText();
        boolean ch = true;
        

        Connection con = null;
        Statement state = null;
        ResultSet result = null;
        String query = "SELECT * FROM student";
        
        if(name.equals("Full Name")||date .equals("Birth Date") || adress_2.equals("Adress") || email_2.equals("Email") || phone_2.equals("Phone")|| rn.equals("Registration Number"))
        {
			JOptionPane.showMessageDialog(null, "please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);

        }
        else {
           
            try {
                con = DriverManager.getConnection("jdbc:sqlite:school.db");
               System.out.println("gfdg");
                state = con.createStatement();
                result = state.executeQuery(query);
                while(result.next())
                {
                    String rn_2 = result.getString("RN");
                    String em  = result.getString("email");
                    if(rn_2.equals(rn) || em.equals(email_2))
                    {
            			JOptionPane.showMessageDialog(null,"the Registration Number or email you have entered is already exist !","warning",JOptionPane.WARNING_MESSAGE);
            			ch = false;

                    }
             
                    
                }
                
                if(ch)
                {
                	String value = "('"+rn+"','"+name+"' , '"+gender_2+"' , '"+date+"','"+adress_2+"','"+phone_2+"','"+email_2+"','"+standard+"')";
                	System.out.println(value);
                	System.out.println(value);
                	state.executeUpdate("INSERT INTO student(RN,Name,gender,birthDate,adress,phone,email,standard) values "+value);
                	
        			JOptionPane.showMessageDialog(null,"Student added successfully !","info",JOptionPane.INFORMATION_MESSAGE);
            		RN.setText("Registration Number");
            		FN.setText("Full Name");
            		BD.setText("Birth Date");
            		adress.setText("Adress");
            		phone.setText("Phone");
            		email.setText("Email");
            		ST1.setText("Standard");

                	
                }
                
            } catch (Exception ex) {
    			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
    }
        }	
    }//GEN-LAST:event_addActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    	homePage home = new homePage();
    	this.setVisible(false);
    	home.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BD;
    private javax.swing.JTextField FN;
    private javax.swing.JTextField RN;
    private javax.swing.JTextField ST1;
    private javax.swing.JButton add;
    private javax.swing.JTextField adress;
    private javax.swing.JButton back;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
