/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school;

import java.time.format.DateTimeFormatter;
import java.util.Calendar;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.time.LocalDateTime;  
/**
 *
 * @author Diaa Dwikat
 */
public class attendance extends javax.swing.JFrame {

    /**
     * Creates new form attendance
     */

	 DefaultTableModel dt;


    public attendance() {
        initComponents();
        dt = (DefaultTableModel) jTable1.getModel();
        this.load();
        this.load_2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        FN = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(133, 180, 220));

        jPanel1.setBackground(new java.awt.Color(60, 66, 74));

        jLabel1.setIcon(new javax.swing.ImageIcon("school svg\\edit\\ti_ATT (1).png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        date.setBackground(new java.awt.Color(60, 66, 74));
        date.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        date.setText(dateFormat.format(cal.getTime()).toString());
        date.setBorder(null);
        date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFocusLost(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persent","Absent" }));

        jLabel7.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        add.setBackground(new java.awt.Color(240, 238, 200));
        add.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add.setForeground(new java.awt.Color(0, 51, 51));
        add.setText("EDIT ATTENDANCE DETAILS");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add1.setBackground(new java.awt.Color(133, 180, 220));
        add1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add1.setForeground(new java.awt.Color(0, 51, 51));
        add1.setText("SAVE ATTENDANCE DETAILS");
        add1.setBorder(null);
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        ID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID");

        FN.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FN.setForeground(new java.awt.Color(255, 255, 255));
        FN.setText("Full Name");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("school svg\\edit\\page (1).png")); // NOI18N

        jTable1.setBackground(new java.awt.Color(60, 66, 74));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(133, 180, 220));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Registration Number", "Name", "Date", "Attendance"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add2.setBackground(new java.awt.Color(65, 80, 107));
        add2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add2.setForeground(new java.awt.Color(204, 204, 204));
        add2.setText("BACK");
        add2.setBorder(null);
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents]



 

    private void dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusGained
        // TODO add your handling code here:
        if(date.getText().equals("DATE"))
            date.setText("");
    }//GEN-LAST:event_dateFocusGained

    private void dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusLost
        // TODO add your handling code here:
        if(date.getText().equals(""))
            date.setText("DATE");
    }//GEN-LAST:event_dateFocusLost

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    	String id = ID.getText();
        String rn = jComboBox2.getSelectedItem().toString();
        String att = jComboBox1.getSelectedItem().toString();
        String name = FN.getText();
        String date_1 = date.getText();
        Connection  connection = null;
        Statement statement = null;
        String sql = "set date = '"+date_1+"', att = '"+att+"'";
        String sql_2 = " where RN = '"+rn+"' and ID = '"+id+"'";
        if( date.equals(null))
        {
            JOptionPane.showMessageDialog(null, "please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);
        }

        try {

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            int Re = JOptionPane.showConfirmDialog(null, "Do you want to update the attendance ?","Question",JOptionPane.YES_NO_OPTION);

            if(Re==0) {
                statement.executeUpdate("update attendance "+sql+sql_2);
                JOptionPane.showMessageDialog(null, "Attendance updated successfully!","info",JOptionPane.INFORMATION_MESSAGE);
                connection.close();

            }

        } catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);

        }
        load_2();
    }//GEN-LAST:event_addActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
    	
        String rn = jComboBox2.getSelectedItem().toString();
        String att = jComboBox1.getSelectedItem().toString();
        String date2 = date.getText();
        String name = FN.getText();
        Connection  connection = null;
        Statement statement = null;
        ResultSet result = null;
        String sql = "VALUES ('"+rn+"','"+name+"','"+date2+"','"+att+"')";
        if(date2.equals(""))
        {
            JOptionPane.showMessageDialog(null, "please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);
        }
        try {

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            statement.executeUpdate("INSERT INTO attendance (RN,name,date,att) "+sql);
            JOptionPane.showMessageDialog(null, "attendance add successfully!","info",JOptionPane.INFORMATION_MESSAGE);
            connection.close();

        } catch (Exception e2) {

			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);

        }
        load_2();

    	
    }//GEN-LAST:event_add1ActionPerformed
    

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
    	homePage home = new homePage();
    	this.setVisible(false);
    	home.setVisible(true);
    }//GEN-LAST:event_add2ActionPerformed

    public void load() {
		System.out.println("hh");
    	

        Connection  connection = null;
        Statement statement = null;
        ResultSet result = null;

        
        try {
        	
        	connection = DriverManager.getConnection("jdbc:sqlite:school.db");
        	statement = connection.createStatement();
        	result = statement.executeQuery("SELECT RN,Name FROM student");
        	while(result.next())
        	{
        		String name = result.getString("Name");
        		String id = result.getString("RN");
        		jComboBox2.addItem(id);

        	}
        	connection.close();
        	
		} catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);

		}
		
	}
    public void load_2() {
    	
    	System.out.println("load");
		dt.setRowCount(0);

        Connection connection = null ;
        Statement state = null;
        ResultSet result = null;
        try {
			connection = DriverManager.getConnection("jdbc:sqlite:school.db");
			state = connection.createStatement();
			result = state.executeQuery("SELECT * FROM attendance");
			while(result.next())
			{
				String id_2 = result.getString("ID");
				String id = result.getString("RN");
				String name = result.getString("Name");
				String date = result.getString("date");
				String att = result.getString("att");
			
				Object[] o = {id_2,id,name,date,att};
				dt.addRow(o);

			}
			connection.close();
		
		} catch (Exception e) {
			// TODO: handle exception

			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);

		}
	}
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        ID.setText(dt.getValueAt(row, 0).toString());
        jComboBox2.setSelectedItem(dt.getValueAt(row,1).toString());
        FN.setText(dt.getValueAt(row,2).toString());
        date.setText(dt.getValueAt(row, 3).toString());
        jComboBox1.setSelectedItem(dt.getValueAt(row,4).toString());
   
  

    }//GEN-LAST:event_jTable1MouseClicked
    
    
    

    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        Connection  connection = null;
        Statement statement = null;
        ResultSet result = null;
        String rn = jComboBox2.getSelectedItem().toString();
        String sql = "where RN = '"+rn+"'";
        try {

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            result = statement.executeQuery("SELECT Name FROM student "+sql);
            String name = result.getString("Name");
            FN.setText(name);
            connection.close();
            
        } catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);

        }
        
        

        
  

    }//GEN-LAST:event_jComboBox1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FN;
    private javax.swing.JLabel ID;
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
