package school;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diaa Dwikat
 */
public class edit extends javax.swing.JFrame {

    /**
     * Creates new form edit
     */
	 DefaultTableModel dt;

    public edit() {
        initComponents();
        dt = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        ST = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RN = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 66, 74));
        jPanel1.setPreferredSize(new java.awt.Dimension(1373, 813));

        jLabel2.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jTable1.setBackground(new java.awt.Color(60, 66, 74));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(133, 180, 220));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration Number", "Name", "Gender", "Birth Date", "Adress", "Phone", "Email", "Standard"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        FN.setBackground(new java.awt.Color(60, 66, 74));
        FN.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        FN.setForeground(new java.awt.Color(255, 255, 255));
        FN.setText("Full Name");
        FN.setBorder(null);
        FN.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        FN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FNFocusLost(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        BD.setBackground(new java.awt.Color(60, 66, 74));
        BD.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BD.setForeground(new java.awt.Color(255, 255, 255));
        BD.setText("Birth Date");
        BD.setBorder(null);
        BD.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        BD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BDFocusLost(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        adress.setBackground(new java.awt.Color(60, 66, 74));
        adress.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        adress.setForeground(new java.awt.Color(255, 255, 255));
        adress.setText("Adress");
        adress.setBorder(null);
        adress.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        adress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adressFocusLost(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        phone.setBackground(new java.awt.Color(60, 66, 74));
        phone.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone");
        phone.setBorder(null);
        phone.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });

        email.setBackground(new java.awt.Color(60, 66, 74));
        email.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        email.setBorder(null);
        email.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        ST.setBackground(new java.awt.Color(60, 66, 74));
        ST.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        ST.setForeground(new java.awt.Color(255, 255, 255));
        ST.setText("Standard");
        ST.setBorder(null);
        ST.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        ST.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                STFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                STFocusLost(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jButton1.setBackground(new java.awt.Color(234, 84, 84));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(33, 79, 105));
        jButton1.setText("DELETE STUDENT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(148, 168, 176));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(33, 79, 105));
        jButton2.setText("EDIT STUDENT");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        RN.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        RN.setForeground(new java.awt.Color(255, 255, 255));
        RN.setText("Registration Number");

        back.setBackground(new java.awt.Color(148, 168, 176));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(33, 79, 105));
        back.setText("back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("school svg\\edit\\title.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(RN, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(172, 172, 172)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BD, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1311, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        RN.setText(dt.getValueAt(row,0).toString());
        FN.setText(dt.getValueAt(row,1).toString());
        BD.setText(dt.getValueAt(row,3).toString());
        adress.setText(dt.getValueAt(row,4).toString());
        phone.setText(dt.getValueAt(row,5).toString());
        email.setText(dt.getValueAt(row,6).toString());
        ST.setText(dt.getValueAt(row,7).toString());
   
  

    }//GEN-LAST:event_jTable1MouseClicked

    
    
    public void load() {
    	
    	System.out.println("load");
        dt.setRowCount(0);
        Connection connection = null ;
        Statement state = null;
        ResultSet result = null;
        try {
			connection = DriverManager.getConnection("jdbc:sqlite:school.db");
			state = connection.createStatement();
			result = state.executeQuery("SELECT * FROM student");
			while(result.next())
			{
				String id = result.getString("RN");
				String name = result.getString("Name");
				String date = result.getString("birthDate");
				String gender = result.getString("gender");
				String phone = result.getString("phone");
				String email = result.getString("email");
				String adress = result.getString("adress");
				String standard = result.getString("standard");

				Object[] o = {id,name,gender,date,adress,phone,email,standard};
				dt.addRow(o);
			}
    
		
		} catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
		}
	}
    private void FNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FNFocusGained
        // TODO add your handling code here:
        if(FN.getText().equals("Full Name"))
        {
            FN.setText("");
        }

    }//GEN-LAST:event_FNFocusGained

    private void FNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FNFocusLost
        // TODO add your handling code here:
        if(FN.getText().equals(""))
        {
            FN.setText("Full Name");
        }
    }//GEN-LAST:event_FNFocusLost

    private void BDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDFocusGained
        // TODO add your handling code here:
        if(BD.getText().equals("Birth Date"))
        BD.setText("");
    }//GEN-LAST:event_BDFocusGained

    private void BDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BDFocusLost
        // TODO add your handling code here:
        if(BD.getText().equals(""))
        BD.setText("Birth Date");
    }//GEN-LAST:event_BDFocusLost

    private void adressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adressFocusGained
        // TODO add your handling code here:
        if(adress.getText().equals("Adress"))
        adress.setText("");
    }//GEN-LAST:event_adressFocusGained

    private void adressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adressFocusLost
        // TODO add your handling code here:
        if(adress.getText().equals(""))
        adress.setText("Adress");
    }//GEN-LAST:event_adressFocusLost

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
        if(phone.getText().equals("Phone"))
        phone.setText("");
    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
        if(phone.getText().equals(""))
        phone.setText("Phone");
    }//GEN-LAST:event_phoneFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Email"))
        email.setText("");
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().equals(""))
        email.setText("Email");
    }//GEN-LAST:event_emailFocusLost

    private void STFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_STFocusGained
        // TODO add your handling code here:
        if(ST.getText().equals("Standard"))
        ST.setText("");
    }//GEN-LAST:event_STFocusGained

    private void STFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_STFocusLost
        // TODO add your handling code here:
        if(ST.getText().equals(""))
        ST.setText("Standard");
    }//GEN-LAST:event_STFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	Connection connection = null;
    	Statement statement = null;
    	String id = RN.getText();
    	String name = FN.getText();
    	String value = "where RN = '"+id +"'";
    	System.out.println(value);
    
    	
    	try {
    		connection = DriverManager.getConnection("jdbc:sqlite:school.db");
    		statement = connection.createStatement();
    		if(id.equals("") || name.equals(""))
    		{
    			JOptionPane.showMessageDialog(null,"please select a task from table .","warning",JOptionPane.WARNING_MESSAGE);
    		}
    		else {
    			
    	    int deleteIndex = JOptionPane.showConfirmDialog(null,"Are you sure you want t delete this student ?","Delete",JOptionPane.YES_NO_OPTION);
    	    
    	    if(deleteIndex==0) {
    		statement.execute("Delete from student "+value );
    		JOptionPane.showMessageDialog(null,"The task deleted successfully . ","info",JOptionPane.INFORMATION_MESSAGE);
    		load();
    		RN.setText("Registration Number");
    		FN.setText("Full Name");
    		BD.setText("Birth Date");
    		adress.setText("Adress");
    		phone.setText("Phone");
    		email.setText("Email");
    		ST.setText("Standard");
    	    }
    	    
    		}
		} catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
		}
    	
    	
    	
    	
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	
    	Connection connection = null;
    	Statement statement = null;
    	String id = RN.getText();
    	String name = FN.getText();
    	String date = BD.getText();
    	String em = email.getText();
    	String ad = adress.getText();
    	String phone_2 = phone.getText();
    	String standard = ST.getText();
    	String value = " set Name = '"+name+"' , birthdate = '"+date+"',email = '"+em+"', phone = '"+phone_2+"',adress = '"+ad+"',standard = '"+standard+"' where RN = '"+id+"'";
    	System.out.println(value);
    	try {
    		connection = DriverManager.getConnection("jdbc:sqlite:school.db");
    		statement = connection.createStatement();
    		if(id.equals("") || name.equals(""))
    		{
    			JOptionPane.showMessageDialog(null,"please select a task from table .","warning",JOptionPane.WARNING_MESSAGE);
    		}
    		else {
    			
    	    int deleteIndex = JOptionPane.showConfirmDialog(null,"Do you want to update the selected task ?","Delete",JOptionPane.YES_NO_OPTION);
    	    
    	    if(deleteIndex==0) {
    		statement.execute("Update student" + value);
    		JOptionPane.showMessageDialog(null,"The task updated successfully . ","info",JOptionPane.INFORMATION_MESSAGE);
    		load();
    		RN.setText("Registration Number");
    		FN.setText("Full Name");
    		BD.setText("Birth Date");
    		adress.setText("Adress");
    		phone.setText("Phone");
    		email.setText("Email");
    		ST.setText("Standard");
    	    }
    	    
    		}
		} catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
		}
    	
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        homePage home = new homePage();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                edit ed = new edit();
                ed.setVisible(true);
                ed.load();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BD;
    private javax.swing.JTextField FN;
    private javax.swing.JLabel RN;
    private javax.swing.JTextField ST;
    private javax.swing.JTextField adress;
    private javax.swing.JButton back;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
