/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diaa Dwikat
 */
public class event extends javax.swing.JFrame {

    /**
     * Creates new form event
     */
	 DefaultTableModel dt;

    public event() {
        initComponents();
        dt = (DefaultTableModel) jTable1.getModel();
        this.load_2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tit = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        ID1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));


        title.setIcon(new javax.swing.ImageIcon("school svg\\event\\title.png")); // NOI18N

        add.setIcon(new javax.swing.ImageIcon("school svg\\event\\add.png")); // NOI18N
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        edit.setIcon(new javax.swing.ImageIcon("school svg\\event\\edit.png")); // NOI18N
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon("school svg\\event\\delete.png")); // NOI18N
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));


        jTable1.setBackground(new java.awt.Color(60, 66, 74));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(133, 180, 220));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "title", "Date", "Description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID");

        jLabel5.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        tit.setBackground(new java.awt.Color(34, 40, 49));
        tit.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tit.setForeground(new java.awt.Color(255, 255, 255));
        tit.setText("Title");
        tit.setBorder(null);
        tit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                titFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                titFocusLost(evt);
            }
        });

        date.setBackground(new java.awt.Color(34, 40, 49));
        date.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");
        date.setBorder(null);
        date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFocusLost(evt);
            }
        });

        des.setBackground(new java.awt.Color(212, 236, 221));
        des.setColumns(20);
        des.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        des.setForeground(new java.awt.Color(44, 57, 75));
        des.setRows(5);
        jScrollPane2.setViewportView(des);

        ID1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ID1.setForeground(new java.awt.Color(255, 255, 255));
        ID1.setText("Description");

        jLabel1.setIcon(new javax.swing.ImageIcon("school svg\\previous (1).png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(add)
                .addGap(187, 187, 187)
                .addComponent(edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(529, 529, 529)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(402, 402, 402))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tit, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGap(52, 52, 52)
                        .addComponent(ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add)
                    .addComponent(edit)
                    .addComponent(delete))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    

    public void load_2() {
    	
    	System.out.println("load");
		dt.setRowCount(0);

        Connection connection = null ;
        Statement state = null;
        ResultSet result = null;
        try {
			connection = DriverManager.getConnection("jdbc:sqlite:school.db");
			state = connection.createStatement();
			result = state.executeQuery("SELECT * FROM event");
			while(result.next())
			{
				String id_2 = result.getString("ID");
				String tit = result.getString("title");
				String date = result.getString("date");
				String des = result.getString("des");
			
				Object[] o = {id_2,tit,date,des};
				dt.addRow(o);

			}
			connection.close();
		
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
        }

    private void titFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titFocusGained
        if(tit.getText().equals("Title"))
            tit.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_titFocusGained

    private void titFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titFocusLost
        if(tit.getText().equals(""))
            tit.setText("Title");
        // TODO add your handling code here:
    }//GEN-LAST:event_titFocusLost

    private void dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusGained
        // TODO add your handling code here:
        if(date.getText().equals("Date"))
            date.setText("");
    }//GEN-LAST:event_dateFocusGained

    private void dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusLost
        // TODO add your handling code here:
        if(date.getText().equals(""))
            date.setText("Date");
    }//GEN-LAST:event_dateFocusLost

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    	String title = tit.getText();
    	String date_2 = date.getText();
    	String des_1 = des.getText();
    	
    	
    	if(title.equals("Title")||date_2.equals("Date")||des_1.equals(""))
    		JOptionPane.showMessageDialog(null, "Please fill all the filed !","Warning",JOptionPane.WARNING_MESSAGE);
    	else {
    		 Connection  connection = null;
    	        Statement statement = null;
    	        ResultSet result = null;
    	        String sql = "Values ('"+title+"','"+date_2+"','"+des_1+"')";
    	        try {

    	            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
    	            statement = connection.createStatement();
    	            statement.executeUpdate("INSERT INTO event(title,date,des) "+sql);
    	            JOptionPane.showMessageDialog(null, "event add successfully!","info",JOptionPane.INFORMATION_MESSAGE);
                    tit.setText("Title");
                    date.setText("Date");
                    des.setText("");
    	            connection.close();

    	        } catch (Exception e2) {
    	            e2.printStackTrace();
    	        }
    	        load_2();
			
		}
    	
    			}//GEN-LAST:event_addMouseClicked
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        ID.setText(jTable1.getValueAt(row, 0).toString());
        tit.setText(dt.getValueAt(row,1).toString());
        date.setText(dt.getValueAt(row,2).toString());
        des.setText(dt.getValueAt(row,3).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
    	String id = ID.getText();
        String title = tit.getText();
        String date_2 = date.getText();
        String des_2 = des.getText();
        Connection  connection = null;
        Statement statement = null;
        String sql = "set title = '"+title+"', date = '"+date_2+"', des = '"+des_2+"'";
        String sql_2 = " where ID = '"+id+"'";
        if(title.equals("Title")||date_2.equals("Date")|| des_2.equals(""))
        {
            JOptionPane.showMessageDialog(null, "please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);
        }

        try {

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            int Re = JOptionPane.showConfirmDialog(null, "Do you want to update the event ?","Question",JOptionPane.YES_NO_OPTION);

            if(Re==0) {
                statement.executeUpdate("update event "+sql+sql_2);
                JOptionPane.showMessageDialog(null, "event updated successfully!","info",JOptionPane.INFORMATION_MESSAGE);
                tit.setText("Title");
                date.setText("Date");
                des.setText("");
                connection.close();

            }

        } catch (Exception e2) {
            e2.printStackTrace();
        }
        load_2();
    }//GEN-LAST:event_editMouseClicked
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        homePage p = new homePage();
        this.setVisible(false);
        p.setVisible(true);
    }      

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    	String id = ID.getText();
    	Connection connection = null;
    	Statement statement =null;
    	String sql = "where ID = '"+id+"'";
    	if(id.equals(""))
    		JOptionPane.showMessageDialog(null, "please select an event !","warning",JOptionPane.WARNING_MESSAGE);
    	else {
    		try {
				

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            int Re = JOptionPane.showConfirmDialog(null, "Do you want to delete the event ?","Question",JOptionPane.YES_NO_OPTION);

            if(Re==0) {
                statement.executeUpdate("delete from event "+sql);
                JOptionPane.showMessageDialog(null, "event deleted successfully!","info",JOptionPane.INFORMATION_MESSAGE);
                date.setText("Date");
                tit.setText("Title");
                des.setText("");
                connection.close();
            }
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
            load_2();
		}
    }//GEN-LAST:event_deleteMouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel add;
    private javax.swing.JTextField date;
    private javax.swing.JLabel delete;
    private javax.swing.JTextArea des;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tit;
    private javax.swing.JLabel title;
    private javax.swing.JLabel jLabel1;

    
    // End of variables declaration//GEN-END:variables
}
