/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;

/**
 *
 * @author Diaa Dwikat
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
	public static String email_3;
	
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user_1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pass_1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        login_1 = new javax.swing.JLabel();
        setP = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(67, 120, 126));

        jLabel1.setIcon(new javax.swing.ImageIcon("school svg\\Student Login.png")); // NOI18N

        user_1.setBackground(new java.awt.Color(67, 120, 126));
        user_1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        user_1.setForeground(new java.awt.Color(255, 255, 255));
        user_1.setText("USER NAME");
        user_1.setBorder(null);
        user_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_1FocusLost(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        pass_1.setBackground(new java.awt.Color(67, 120, 126));
        pass_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass_1.setForeground(new java.awt.Color(255, 255, 255));
        pass_1.setText("password");
        pass_1.setBorder(null);
        pass_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_1FocusLost(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        login_1.setIcon(new javax.swing.ImageIcon("school svg\\login.png")); // NOI18N
        login_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_1MouseClicked(evt);
            }
        });

        setP.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        setP.setForeground(new java.awt.Color(255, 255, 255));
        setP.setText("Set Password");
        setP.setToolTipText("");
        setP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login_1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(setP, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pass_1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(user_1)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(user_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(57, 57, 57)
                .addComponent(pass_1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(100, 100, 100)
                .addComponent(login_1)
                .addGap(27, 27, 27)
                .addComponent(setP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(24, 66, 73));

        jLabel2.setIcon(new javax.swing.ImageIcon("school svg\\Admin Login.png")); // NOI18N

        user.setBackground(new java.awt.Color(24, 66, 73));
        user.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("USER NAME");
        user.setBorder(null);
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jPasswordField1.setBackground(new java.awt.Color(24, 66, 73));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("password");
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        login.setIcon(new javax.swing.ImageIcon("school svg\\login.png")); // NOI18N
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField1)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(user)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(57, 57, 57)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(103, 103, 103)
                .addComponent(login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_1FocusGained
        // TODO add your handling code here:
       if(user_1.getText().equals("USER NAME"))
        user_1.setText("");
    }//GEN-LAST:event_user_1FocusGained

    private void user_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_1FocusLost
        // TODO add your handling code here:
               if(user_1.getText().equals(""))
                    user_1.setText("USER NAME");
    }//GEN-LAST:event_user_1FocusLost

    private void pass_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_1FocusGained
        // TODO add your handling code here:if
        
        if(pass_1.getText().equals("password"))
            pass_1.setText("");
    }//GEN-LAST:event_pass_1FocusGained

    private void pass_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_1FocusLost
        // TODO add your handling code here:
        if(pass_1.getText().equals(""))
            pass_1.setText("password");
    }//GEN-LAST:event_pass_1FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
                if(jPasswordField1.getText().equals("password"))
                    jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
                if(jPasswordField1.getText().equals(""))
                    jPasswordField1.setText("password");
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        // TODO add your handling code here:
        if(user.getText().equals("USER NAME"))
            user.setText("");
    }//GEN-LAST:event_userFocusGained

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        // TODO add your handling code here:
        if(user.getText().equals(""))
            user.setText("USER NAME");
    }//GEN-LAST:event_userFocusLost

    private void login_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_1MouseClicked
        // TODO add your handling code here:
    	String userName = user_1.getText();
    	String password = pass_1.getText();
    	Connection connection = null;
    	boolean ch = false;
    	Statement statement = null;
    	ResultSet result = null;
    	if(userName.equals("USER NAME")||password.equals("password"))
    	{
    		JOptionPane.showMessageDialog(null, "Please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);
    	}
    	else {
    	try {
			connection = DriverManager.getConnection("jdbc:sqlite:school.db");
			statement = connection.createStatement();
			result = statement.executeQuery("select email,password,name,RN from student");
			String name = "";
			String rn = "";
			while(result.next())
			{
				String email = result.getString("email");
				String passw = result.getString("password");
				rn = result.getString("RN");
				name = result.getString("name");
				if(userName.equals(email)&&password.equals(passw))
				{
					ch = true;
					email_3 = rn;
					break;
					
				}
			}
		if(ch)
		{
			
			studentPage sp = new studentPage();
			st_att at = new st_att();
			mark_st m = new mark_st();
			at.email=email_3;
			m.email = email_3;
			this.setVisible(false);
			sp.name_set(name.toUpperCase());
			sp.setVisible(true);
		}
		else {
    		JOptionPane.showMessageDialog(null, "wrong password or user name !","warning",JOptionPane.ERROR_MESSAGE);

		}

			
    	}

			
		catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
		}
    	}
    }//GEN-LAST:event_login_1MouseClicked

    private void setPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPMouseClicked
        // TODO add your handling code here:
    	password p = new password();
    	this.setVisible(false);
    	p.setVisible(true);
    	
    }//GEN-LAST:event_setPMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
    	String userName = user.getText();
    	String pass = jPasswordField1.getText();
    	if(userName.equals("diaa") && pass.equals("1234"))
    	{
    		
    		homePage home = new homePage();
    		this.setVisible(false);
    		home.setVisible(true);
    	}
    	else {
			JOptionPane.showMessageDialog(null, "the password or user name is wrong !","error",JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel login_1;
    private javax.swing.JPasswordField pass_1;
    private javax.swing.JLabel setP;
    private javax.swing.JTextField user;
    private javax.swing.JTextField user_1;
    // End of variables declaration//GEN-END:variables
}
