/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Diaa Dwikat
 */
public class mark extends javax.swing.JFrame {

    /**
     * Creates new form mark
     */
	 DefaultTableModel dt;

    public mark() {
        initComponents();
        this.load();
        dt = (DefaultTableModel) jTable1.getModel();
        this.load_2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SC = new javax.swing.JTextField();
        EE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        FN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 66, 74));
        jPanel1.setMaximumSize(new java.awt.Dimension(1373, 813));
        jPanel1.setMinimumSize(new java.awt.Dimension(1373, 813));

        jComboBox1.setBackground(new java.awt.Color(60, 66, 74));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        SC.setBackground(new java.awt.Color(60, 66, 74));
        SC.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        SC.setForeground(new java.awt.Color(255, 255, 255));
        SC.setText("Score");
        SC.setBorder(null);
        SC.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        SC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SCFocusLost(evt);
            }
        });

        EE.setBackground(new java.awt.Color(60, 66, 74));
        EE.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        EE.setForeground(new java.awt.Color(255, 255, 255));
        EE.setText("Exam Effective");
        EE.setBorder(null);
        EE.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        EE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EEFocusLost(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        add.setBackground(new java.awt.Color(148, 168, 176));
        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(33, 79, 105));
        add.setText("ADD MARK");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(148, 168, 176));
        edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(33, 79, 105));
        edit.setText("EDIT MARK");
        edit.setBorder(null);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(234, 84, 84));
        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(33, 79, 105));
        delete.setText("DELETE MARK");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(60, 66, 74));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(133, 180, 220));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Registration Number", "Name", "Lecture Name", "Exam Type", "Score", "Exam Effective"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        back.setBackground(new java.awt.Color(148, 168, 176));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(33, 79, 105));
        back.setText("back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(60, 66, 74));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Math", "Physics", "Pieology", "Chemistry" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        FN.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        FN.setForeground(new java.awt.Color(255, 255, 255));
        FN.setText("Full Name");

        jLabel1.setIcon(new javax.swing.ImageIcon("school svg\\edit\\mark.png")); // NOI18N

        jComboBox3.setBackground(new java.awt.Color(60, 66, 74));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quiz","Midterm","Final" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");

        jLabel9.setIcon(new javax.swing.ImageIcon("school svg\\addStudentPage\\line.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(70, 70, 70)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(68, 68, 68)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SC, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EE, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 107, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(558, 558, 558))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(FN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        homePage homePag = new homePage();
        this.setVisible(false);
        homePag.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        jLabel8.setText(jTable1.getValueAt(row, 0).toString());
        jComboBox1.setSelectedItem(dt.getValueAt(row,1).toString());
        FN.setText(dt.getValueAt(row,2).toString());
        jComboBox2.setSelectedItem(dt.getValueAt(row,3).toString());
        jComboBox3.setSelectedItem(dt.getValueAt(row,4).toString());
        SC.setText(dt.getValueAt(row,5).toString());
        EE.setText(dt.getValueAt(row,6).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String rn = jComboBox1.getSelectedItem().toString();
        String LC = jComboBox2.getSelectedItem().toString();
        String type = jComboBox3.getSelectedItem().toString();
        String name = FN.getText();
        String score = SC.getText();
        String exam_ef = EE.getText();
        Connection  connection = null;
        Statement statement = null;
        String sql = "WHERE RN = '"+rn+"' AND lectureName = '"+LC+"' AND examType = '"+type+"'AND score = '"+score+"'AND examEf='"+exam_ef+"'";
        if(score.equals("Score") || exam_ef.equals("Exam Effective"))
        {
            JOptionPane.showMessageDialog(null, "please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);
        }

        try {
        		//jdbc:sqlite:/d:\\ java project\\school\\school.db
            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            int Re = JOptionPane.showConfirmDialog(null, "Do you want to delete the mark ?","Question",JOptionPane.YES_NO_OPTION);

            if(Re==0) {
                statement.executeUpdate("delete from mark "+sql);
                JOptionPane.showMessageDialog(null, "Mark deleted successfully!","info",JOptionPane.INFORMATION_MESSAGE);
                SC.setText("Score");
                EE.setText("Exam Effective");
                connection.close();

            }

        } catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
        }
        load_2();
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    	String ID = jLabel8.getText();
        String rn = jComboBox1.getSelectedItem().toString();
        String LC = jComboBox2.getSelectedItem().toString();
        String type = jComboBox3.getSelectedItem().toString();
        String name = FN.getText();
        String score = SC.getText();
        String exam_ef = EE.getText();
        Connection  connection = null;
        Statement statement = null;
        String sql = "set lectureName = '"+LC+"', examType = '"+type+"', score = '"+score+"', examEf='"+exam_ef+"'";
        String sql_2 = " where RN = '"+rn+"' and ID = '"+ID+"'";
        if(score.equals("Score") || exam_ef.equals("Exam Effective"))
        {
            JOptionPane.showMessageDialog(null, "please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);
        }

        try {

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            int Re = JOptionPane.showConfirmDialog(null, "Do you want to update the mark ?","Question",JOptionPane.YES_NO_OPTION);

            if(Re==0) {
                statement.executeUpdate("update mark "+sql+sql_2);
                JOptionPane.showMessageDialog(null, "Mark updated successfully!","info",JOptionPane.INFORMATION_MESSAGE);
                SC.setText("Score");
                EE.setText("Exam Effective");
                connection.close();

            }

        } catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
        }
        load_2();
    }//GEN-LAST:event_editActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String rn = jComboBox1.getSelectedItem().toString();
        String LC = jComboBox2.getSelectedItem().toString();
        String type = jComboBox3.getSelectedItem().toString();
        String name = FN.getText();
        String score = SC.getText();
        String exam_ef = EE.getText();
        Connection  connection = null;
        Statement statement = null;
        ResultSet result = null;
        String sql = "VALUES ('"+rn+"','"+name+"','"+LC+"','"+type+"','"+score+"','"+exam_ef+"')";
        if(score.equals("Score") || exam_ef.equals("Exam Effective"))
        {
            JOptionPane.showMessageDialog(null, "please fill all the field !","warning",JOptionPane.WARNING_MESSAGE);
        }

        try {

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            statement.executeUpdate("INSERT INTO mark(RN,name,lectureName,examType,score,examEf) "+sql);
            JOptionPane.showMessageDialog(null, "Mark add successfully!","info",JOptionPane.INFORMATION_MESSAGE);
            SC.setText("Score");
            EE.setText("Exam Effective");
            connection.close();

        } catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
        }
        load_2();

    }//GEN-LAST:event_addActionPerformed

    private void EEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EEFocusLost
        // TODO add your handling code here:
        if(EE.getText().equals(""))
        EE.setText("Exam Effective");
    }//GEN-LAST:event_EEFocusLost

    private void EEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EEFocusGained
        // TODO add your handling code here:
        if(EE.getText().equals("Exam Effective"))
        EE.setText("");
    }//GEN-LAST:event_EEFocusGained

    private void SCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SCFocusLost
        // TODO add your handling code here:
        if(SC.getText().equals(""))
        SC.setText("Score");
    }//GEN-LAST:event_SCFocusLost

    private void SCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SCFocusGained
        // TODO add your handling code here:
        if(SC.getText().equals("Score"))
        SC.setText("");
    }//GEN-LAST:event_SCFocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        Connection  connection = null;
        Statement statement = null;
        ResultSet result = null;
        String rn = jComboBox1.getSelectedItem().toString();
        String sql = "where RN = '"+rn+"'";
        try {

            connection = DriverManager.getConnection("jdbc:sqlite:school.db");
            statement = connection.createStatement();
            result = statement.executeQuery("SELECT Name FROM student "+sql);
            String name = result.getString("Name");
            FN.setText(name);
            connection.close();
        } catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
        }
        
        load_2() ;

    }//GEN-LAST:event_jComboBox1ActionPerformed


    
    public void load() {
		System.out.println("hh");
    	

        Connection  connection = null;
        Statement statement = null;
        ResultSet result = null;
        boolean check = false;
        boolean check2 = true;
        
        try {
        	
        	connection = DriverManager.getConnection("jdbc:sqlite:school.db");
        	statement = connection.createStatement();
        	result = statement.executeQuery("SELECT RN,Name FROM student");
        	while(result.next())
        	{
        		String name = result.getString("Name");
        		String id = result.getString("RN");
        		jComboBox1.addItem(id);

        	}
        	connection.close();
        	
		} catch (Exception e2) {
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
		}
		
	}
    
        
    public void load_2() {
    	
    	System.out.println("load");

        Connection connection = null ;
        Statement state = null;
        ResultSet result = null;
        try {
			connection = DriverManager.getConnection("jdbc:sqlite:school.db");
			state = connection.createStatement();
			result = state.executeQuery("SELECT * FROM mark where RN = '"+jComboBox1.getSelectedItem().toString()+"'");

			if(dt!=null)
			{    	dt.setRowCount(0);

			while(result.next())
			{
				String id_2 = result.getString("ID");
				String id = result.getString("RN");
				String name = result.getString("Name");
				String LC = result.getString("lectureName");
				String ET = result.getString("examType");
				String score = result.getString("score");
				String EE = result.getString("examEF");
				Object[] o = {id_2,id,name,LC,ET,score,EE};
				dt.addRow(o);

			}
			
			}
			
			connection.close();
		
		} catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null,"something went wrong","warning",JOptionPane.WARNING_MESSAGE);
		}
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mark().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EE;
    private javax.swing.JLabel FN;
    private javax.swing.JTextField SC;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
